local c = require("core.palette")
local syntax_cyan = c.syntax_cyan or c.cyan

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = c.colorscheme
vim.o.background = "dark"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal",        { fg = c.fg, bg = "NONE" })
hi("NormalNC",      { fg = c.fg, bg = "NONE" })
hi("NormalFloat",   { fg = c.fg, bg = "NONE" })
hi("FloatBorder",   { fg = c.muted, bg = "NONE" })
hi("EndOfBuffer",   { fg = c.bg, bg = "NONE" })
hi("Cursor",        { fg = c.bg, bg = c.accent })
hi("CursorLine",    { bg = c.surface })
hi("LineNr",        { fg = c.muted })
hi("CursorLineNr",  { fg = c.accent, bold = true })
hi("SignColumn",    { bg = "NONE" })
hi("Visual",        { bg = c.surface_alt })
hi("Search",        { fg = c.white, bg = c.accent })
hi("IncSearch",     { fg = c.white, bg = c.accent_alt })
hi("Pmenu",         { fg = c.fg, bg = "NONE" })
hi("PmenuSel",      { fg = c.white, bg = c.accent })
hi("StatusLine",    { fg = c.fg, bg = c.surface })
hi("StatusLineNC",  { fg = c.muted, bg = "NONE" })
hi("VertSplit",     { fg = c.surface_alt })
hi("WinSeparator",  { fg = c.surface_alt })
hi("TabLine",       { fg = c.muted, bg = "NONE" })
hi("TabLineSel",    { fg = c.fg, bg = c.surface })

hi("Comment",     { fg = c.muted, italic = true })
hi("Constant",    { fg = c.yellow })
hi("String",      { fg = c.green })
hi("Character",   { fg = c.green })
hi("Number",      { fg = c.yellow })
hi("Boolean",     { fg = c.yellow })
hi("Float",       { fg = c.yellow })
hi("Identifier",  { fg = c.fg })
hi("Function",    { fg = c.blue })
hi("Statement",   { fg = c.accent })
hi("Conditional", { fg = c.accent })
hi("Repeat",      { fg = c.accent })
hi("Label",       { fg = c.accent })
hi("Operator",    { fg = syntax_cyan })
hi("Keyword",     { fg = c.accent })
hi("Exception",   { fg = c.accent })
hi("PreProc",     { fg = c.magenta })
hi("Include",     { fg = c.magenta })
hi("Define",      { fg = c.magenta })
hi("Macro",       { fg = c.magenta })
hi("Type",        { fg = syntax_cyan })
hi("StorageClass",{ fg = syntax_cyan })
hi("Structure",   { fg = syntax_cyan })
hi("Special",     { fg = c.magenta })
hi("Underlined",  { fg = c.blue, underline = true })
hi("Error",       { fg = c.red, bold = true })
hi("Todo",        { fg = c.bg, bg = c.yellow, bold = true })

hi("DiagnosticError",          { fg = c.red })
hi("DiagnosticWarn",           { fg = c.yellow })
hi("DiagnosticInfo",           { fg = c.blue })
hi("DiagnosticHint",           { fg = syntax_cyan })
hi("DiagnosticUnderlineError", { sp = c.red,    undercurl = true })
hi("DiagnosticUnderlineWarn",  { sp = c.yellow, undercurl = true })
hi("DiagnosticUnderlineInfo",  { sp = c.blue,   undercurl = true })
hi("DiagnosticUnderlineHint",  { sp = syntax_cyan, undercurl = true })

hi("TelescopeNormal",       { fg = c.fg, bg = "NONE" })
hi("TelescopeBorder",       { fg = c.muted, bg = "NONE" })
hi("TelescopeSelection",    { fg = c.fg, bg = c.surface })
hi("TelescopeMatching",     { fg = c.accent, bold = true })
hi("TelescopePromptPrefix", { fg = c.accent })
