-- Generated by chezmoi from .chezmoidata.yaml. Do not edit directly.
-- Change theme by editing ~/.config/chezmoi/chezmoi.toml and running: chezmoi apply
return {
  name         = "rose",
  colorscheme  = "chezmoi-rose",
  bg           = "#08090a",
  fg           = "#d7d7d7",
  surface      = "#1f2328",
  surface_alt  = "#2a2f35",
  surface_dark = "#15171a",
  muted        = "#5f6368",
  subtle       = "#858585",
  accent       = "#e11d48",
  accent_alt   = "#ff4d6d",
  success      = "#a6d189",
  warning      = "#f9d56e",
  info         = "#89b4fa",
  secondary    = "#f5a6c8",
  cyan         = "#89dceb",
  danger       = "#ff5f87",
  white        = "#ffffff",

  green        = "#a6d189",
  yellow       = "#f9d56e",
  blue         = "#89b4fa",
  magenta      = "#f5a6c8",
  red          = "#ff6b8a",
  syntax_cyan  = "#89dceb",
}
